# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(969, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 11, 171, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(167, 173, 255);")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 160, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 220, 171, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(610, 220, 151, 21))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 469, 160, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(260, 580, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(610, 470, 160, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_3.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_3.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_3.addWidget(self.lineEdit_7)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(650, 560, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(189, 20, 231, 201))
        self.widget.setStyleSheet("background-color: rgb(184, 196, 197);")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 30, 81, 191))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(826, 30, 81, 181))
        self.label_3.setObjectName("label_3")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(570, 20, 231, 201))
        self.widget_2.setStyleSheet("background-color: rgb(184, 196, 197);")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(190, 260, 231, 201))
        self.widget_3.setStyleSheet("background-color: rgb(184, 196, 197);")
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(580, 260, 231, 201))
        self.widget_4.setStyleSheet("background-color: rgb(184, 196, 197);")
        self.widget_4.setObjectName("widget_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ###self.add_functions() (тут убрать решетки, чтобы кнопки жмякались)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Window"))
        self.label.setText(_translate("MainWindow", "Выберите режим работы"))
        self.pushButton.setText(_translate("MainWindow", "Контроль людей"))
        self.pushButton_2.setText(_translate("MainWindow", "Добавить человека"))
        self.pushButton_3.setText(_translate("MainWindow", "Контроль ТС"))
        self.pushButton_4.setText(_translate("MainWindow", "Добавить ТС"))
        self.pushButton_6.setText(_translate("MainWindow", "Пропустить"))
        self.pushButton_8.setText(_translate("MainWindow", "Пропустить"))
        self.lineEdit.setText(_translate("MainWindow", "Фамилия:"))
        self.lineEdit_2.setText(_translate("MainWindow", "Имя:"))
        self.lineEdit_3.setText(_translate("MainWindow", "Отчество:"))
        self.lineEdit_4.setText(_translate("MainWindow", "Должность:"))
        self.pushButton_9.setText(_translate("MainWindow", "Сохранить"))
        self.lineEdit_5.setText(_translate("MainWindow", "Марка:"))
        self.lineEdit_6.setText(_translate("MainWindow", "Модель:"))
        self.lineEdit_7.setText(_translate("MainWindow", "Гос. номер:"))
        self.pushButton_10.setText(_translate("MainWindow", "Сохранить"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))

    """def add_functions(self):
        self.pushButton.clicked.connect(self.can)
        self.pushButton_2.clicked.connect(self.open)
        self.pushButton_3.clicked.connect(self.can)
        self.pushButton_4.clicked.connect(self.open)
        self.pushButton_6.clicked.connect(self.razr)
        self.pushButton_8.clicked.connect(self.razr2)
        self.pushButton_9.clicked.connect(self.saveFaces)
        self.pushButton_9.clicked.connect(self.saveTC)

        self.thread = ThreadOpenCV()  # +++
        self.thread.changePixmap.connect(self.setImage)
    def razr(self):
        print("Допуск разрешен")
    def razr2(self):
        print("Въезд разрешен")
    def can(self):
        self.thread.start()  # +++

    def setImage(self, image):  # +++
        self.label_video.setPixmap(QPixmap.fromImage(image))  # +++

    def openImage(self, image):
        pixmapImage = QPixmap(image)
        pixmapImage = pixmapImage.scaled(
            300, 300,
            Qt.KeepAspectRatio,
            Qt.SmoothTransformation
        )
        self.labelImage.setPixmap(pixmapImage)

    def open(self):
        fileName, _ = QFileDialog.getOpenFileName(
            self,
            "Open Image",
            QDir.currentPath(),
            "Image Files (*.png *.jpg *.bmp)"
        )
        if fileName:
            self.image = fileName
            self.openImage(fileName)

    def imageClicked(self):
        self.window = QLabel()
        self.window.setPixmap(QPixmap(self.image))
        self.window.show()
        self.window.activateWindow()"""
###Верхнюю часть раскоментить и сделать функции правильные, чтобы когда кнопка жмякалась, они выполнялись)
        
                                          
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
